version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - "5432:5432" # Expose the database on the default port
    environment:
      POSTGRES_USER: c5rogers
      POSTGRES_PASSWORD: natiman
      POSTGRES_DB: test
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistent storage

volumes:
  postgres_data:
